version: 2.0
jobs:
  check_for_updates:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-app-db-cache
      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run:
          name: Check current version of node
          command: node -v
      - run:
          name: Install dependencies
          command: |
            sudo gem install fastlane
            npm install @slack/client@3.16.0 --save
            npm install dirty --save
            npm install moment --save
      - run:
          name: Poll itc changes
          command: node poll-itc.js
      - save_cache:
          key: v1-app-db-cache
          paths:
            - /home/circleci/project/kvstore.db
workflows:
  version: 2
  build_on_push:
    jobs:
      - check_for_updates
  check_ios_apps_status:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - check_for_updates
